### ISSUE TITLE
Delete element using delete button from the keyboard 

### ISSUE THREAD

**Issue by shahronak47** [rstudio/shinyuieditor#131]
Can we add a possibility to delete an element using the delete button on the keyboard? Right now if you want to delete an element, you select that element and click "Delete element" button on the UI of shinyuieditor but I think it will be useful to also have a possibility to delete it by pressing delete button from the keyboard .

**Comment by nstrayer** [comment]
Hi @shahronak47 , 

Sorry for the delay on responding to this -- holidays have me behind!

This is a great idea and I find myself trying to delete elements with the keyboard, too. Probably a good sign it's a necessary feature. 

One fear I have is it will make it easy to accidentally delete something, do you think there should be a confirm prompt or is the ability to use the undo button enough to keep it safe?

**Comment by shahronak47** [comment]
If I'm able to delete the element from the keyboard I would also expect to undo the operation from the keyboard using Command + Z (Ctrl + Z).

**Comment by nstrayer** [comment]
We think alike! I've got a PR up for the dev branch (#135) that implements both delete, undo, and redo as keyboard shortcuts. Early next week I should have a release with the new dev branch features. Once it's all merged I'll update here.

**Comment by nstrayer** [comment]
Sorry for the delay! We were waiting on getting credentials to publish to the visual studio code marketplace on that PR. Now it's done and merged with main in #138 so keyboard extensions are available! Thanks for the feedback!
