### ISSUE TITLE
Grids with single rows or columns

### ISSUE THREAD

**Issue by kramerrs** [rstudio/shinyuieditor#144]
When editing grids sometimes I would delete all but a single column, this would cause an issue rendering in shiny and freezing in shinyuieditor.  While, I realized this isn't necessary, because I could span two rows or two columns by dragging an element to take up more than one space, it should cause freezing and generating bad app.R files if that is the case.  Also a help tip here would be nice.

**Comment by nstrayer** [comment]
Out of curiousity is this still an issue with the latest versions? The following app renders fine for me. There absolutely was a time where single column/row grids broke things though, but I thought I had fixed it. 

```
library(shiny)
library(gridlayout)
library(bslib)

ui <- grid_page(
  layout = c(
    "header ",
    "newPlot"
  ),
  row_sizes = c(
    "100px",
    "0.97fr"
  ),
  col_sizes = c(
    "1fr"
  ),
  gap_size = "1rem",
  grid_card_text(
    area = "header",
    content = "Single Column",
    alignment = "start"
  ),
  grid_card_plot(area = "newPlot")
)

server <- function(input, output) {
}

shinyApp(ui, server)
```
