### ISSUE TITLE
launch_editor fails when using reactive({})

### ISSUE THREAD

**Issue by TiagoOlivoto** [rstudio/shinyuieditor#148]
Hi!
First of all, thank you so much for the impressive package!

I've noticed an issue when using reactive({}) in my code. In brief, when using reactive({}), for example, to create an internal data.frame and make it available for several procedures, the command shinyuieditor::launch_editor(app_loc = "...") doesn't open the editor. The shiny application, however, works as expected. Here's a minimal example (assuming that this is saved in app.R within the working directory 'myfolder'

``` r
library(shiny)
library(gridlayout)
library(bslib)


ui <- navbarPage(
  title = "Chick Weights",
  selected = "Empty Tab",
  collapsible = TRUE,
  theme = bslib::bs_theme(),
  tabPanel(
    title = "Empty Tab",
    grid_container(
      layout = c(
        "nums square",
        "nums square"
      ),
      row_sizes = c(
        "1fr",
        "1fr"
      ),
      col_sizes = c(
        "1fr",
        "1fr"
      ),
      gap_size = "10px",
      grid_card(
        area = "nums",
        full_screen = TRUE,
        card_header("Header"),
        card_body_fill(
          sliderInput(
            inputId = "inputId",
            label = "Slider Input",
            min = 0,
            max = 10,
            value = 5,
            width = "100%"
          )
        )
      ),
      grid_card(
        area = "square",
        full_screen = TRUE,
        card_header("Header"),
        card_body_fill(textOutput(outputId = "squared"))
      )
    )
  )
)


server <- function(input, output) {
  numsqr <- reactive({input$inputId ^ 2})

output$squared <- renderText({
  paste0("the square of ", input$inputId, " is ", numsqr())
})

}

shinyApp(ui, server)

```

Then, running 
```r
shinyuieditor::launch_editor(app_loc = "myfolder/")
```
 Do not open the editor, as can be seen in the following PrintScreen

![dontwork](https://user-images.githubusercontent.com/34458429/226119248-e991a22d-92a8-4f71-95d2-d39b05cd4e52.png)

Now, without reactive() it works

```r
library(shiny)
library(gridlayout)
library(bslib)


ui <- navbarPage(
  title = "Chick Weights",
  selected = "Empty Tab",
  collapsible = TRUE,
  theme = bslib::bs_theme(),
  tabPanel(
    title = "Empty Tab",
    grid_container(
      layout = c(
        "nums square",
        "nums square"
      ),
      row_sizes = c(
        "1fr",
        "1fr"
      ),
      col_sizes = c(
        "1fr",
        "1fr"
      ),
      gap_size = "10px",
      grid_card(
        area = "nums",
        full_screen = TRUE,
        card_header("Header"),
        card_body_fill(
          sliderInput(
            inputId = "inputId",
            label = "Slider Input",
            min = 0,
            max = 10,
            value = 5,
            width = "100%"
          )
        )
      ),
      grid_card(
        area = "square",
        full_screen = TRUE,
        card_header("Header"),
        card_body_fill(textOutput(outputId = "squared"))
      )
    )
  )
)


server <- function(input, output) {
output$squared <- renderText({
  paste0("the square of ", input$inputId, " is ", input$inputId^2)
})

}

shinyApp(ui, server)
```

![works](https://user-images.githubusercontent.com/34458429/226119110-5fe10603-f7d8-4ddb-8638-e7d651a81aec.png)

Could this be only on my side? 
Best regards!

<sup>Created on 2023-03-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by nstrayer** [comment]
Okay, so Pr #149 will fix this once it's merged. Turns out the problem was even more general than reactives, but any function call that wasn't a function previously known. 

Here's the result of running the first app above with the code from the PR. 

![Shiny UI Editor](https://user-images.githubusercontent.com/6764693/226387647-438470bf-a735-4528-9365-bdc01b21380c.png)

**Comment by nstrayer** [comment]
Okay. PR merged. You should be good to update with `remotes::install_github("rstudio/shinyuieditor")` and things should be resolved. 
Thanks so much for the clear and helpful issue! It really helps drive the project forward!

**Comment by TiagoOlivoto** [comment]
Thank you so much for your prompt fix! 
I'll try it later.... this will save me a lot of code since I was generating the data inside each render***({}).
Best regards!
