### ISSUE TITLE
Not working even creating a new app from the template in vscode

### ISSUE THREAD

**Issue by Fred-Wu** [rstudio/shinyuieditor#167]
On my Windows 10 machine, after creating an app from `Launch ShinyUIEditor`, and selecting a template, the editor will appear for a few seconds, and then immediately jumps to the error window. 

On my Macbook, even clicking "Next" is not working after choosing a template. 

However, it works if launching from the R package as `shinyuieditor::launch_editor(app_loc = "app.R")`

![image](https://github.com/rstudio/shinyuieditor/assets/4111978/c596a312-c88f-499a-bb08-868145052d51)

![image](https://github.com/rstudio/shinyuieditor/assets/4111978/a13071d5-fe6d-4efc-8e40-949ca0cd6cb2)

**Comment by nstrayer** [comment]
I'm pretty sure this is a problem with the underlying R package getting out of sync with the vscode extension. The vscode extension is always auto updating. 

The fix should be as simple as making sure the R pkg version matches the vscode version and prompting the user to upgrade the r package if there's a mismatch. 

Thanks so much for reporting this (and being one of the few using the extension.)

**Comment by nstrayer** [comment]
This should be fixed as of the latest release #185
