### ISSUE TITLE
Installation Error Not Covered by Main Page

### ISSUE THREAD

**Issue by SolarDifference** [rstudio/shinyuieditor#187]
I'm receiving the following installation error after running the installation instructions on the main page. 

`Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/rstudio/shinyuieditor/tarball/HEAD' failed`

**Comment by grasshoppermouse** [comment]
Same error running `remotes::install_github("rstudio/shinyuieditor")`

**Comment by nstrayer** [comment]
Glad to hear it fixed itself! Please feel free to reopen if the problem comes back!
