### ISSUE TITLE
Support `nav_panel` within apps using the `page_navbar` template

### ISSUE THREAD

**Issue by rpodcast** [rstudio/shinyuieditor#190]
After creating a simple app in the editor based on the navbar template (which had no issues), I decided to try loading a pre-made app based on this [example](https://rstudio.github.io/bslib/articles/dashboards/index.html) with a few modifications. In my adapted example, I'm using `nav_panel` instead of `tabPanel` which is used in the fresh template. Would it be possible to have `nav_panel` supported? I know it's [not trivial](https://rstudio.github.io/shinyuieditor/articles/faqs.html#i-maintain-a-package-with-a-popular-widget-for-shiny-how-can-i-add-that-widget-to-the-shinyuieditor) to add support for additional UI elements coming from separate packages, but this would be a great value to future uses of the editor with `bslib`- powered dashboards.

Example application

```r
library(shiny)
library(bslib)
library(ggplot2)

# install.packages("palmerpenguins")
data(penguins, package = "palmerpenguins")

ui <- page_navbar(
  title = "Penguins dashboard",
  sidebar = selectInput(
    selected = "species",
    inputId = "color_by",
    label = "Color by",
    choices = c(
      "species",
      "island",
      "sex"
    )
  ),
  collapsible = nav_spacer(),
  nav_panel(
        "Bill Length", 
        card(
          full_screen = TRUE,
          card_header("Bill Length"),
          plotOutput("bill_length")
        )
      ),
  nav_panel(
        "Bill Depth", 
        card(
          full_screen = TRUE,
          card_header("Bill depth"),
          plotOutput("bill_depth")
        )
      ),
  nav_panel(
        "Body Mass", 
        card(
          full_screen = TRUE,
          card_header("Body Mass"),
          plotOutput("body_mass")
        )
      ),
  nav_item(tags$a("Posit", href = "https://posit.co"))
)

server <- function(input, output) {
  gg_plot <- reactive({
    ggplot(penguins) +
      geom_density(aes(fill = !!input$color_by), alpha = 0.2) +
      theme_bw(base_size = 16) +
      theme(axis.title = element_blank())
  })
  
  output$bill_length <- renderPlot(gg_plot() + aes(bill_length_mm))
  output$bill_depth <- renderPlot(gg_plot() + aes(bill_depth_mm))
  output$body_mass <- renderPlot(gg_plot() + aes(body_mass_g))
}

shinyApp(ui, server)
```

**Comment by nstrayer** [comment]
As of #215, most of that example app will work. There are a few areas where the UI editor still gets tripped up. 
1. It wants to the sidebar wrapped in a sidebar call. This can/ probably should be updated.
2. It doesn't know how to deal with `collapsible = nav_spacer()`.
3. `nav_item()` isn't supported. (Also, it probably should be.)
