### ISSUE TITLE
Deleting the choice "key" removes the following choice entirely

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/shinyuieditor#197]
Here's a small bug that occurs when you're trying to remove choice keys from a set of choices. (Or alternatively you're trying to edit the choice keys.)

https://github.com/rstudio/shinyuieditor/assets/5420529/03ef1f7a-2ce8-47a5-9f1e-b5d2bb78e958

To reproduce (I think these are the steps, see video for reprex):

1. Open an app and add a checkbox group input.
2. Add a couple more choices to the input.
3. Delete the key for one choice.
4. Delete the key for another choice. The choice whose key was first deleted will be removed entirely.

**Comment by nstrayer** [comment]
This is fixed by #224 as of [#68e6109](https://github.com/rstudio/shinyuieditor/pull/224/commits/68e610973c386bd9d4e916786a6ad017b51480aa)
