### ISSUE TITLE
Hard-to-read text in tour

### ISSUE THREAD

**Issue by jcheng5** [rstudio/shinyuieditor#226]
The text is low contrast and its opacity pulses along with the background

<img width="406" alt="image" src="https://github.com/rstudio/shinyuieditor/assets/129551/00f67928-e87b-4f47-9df9-266023a2d3ac">

**Comment by nstrayer** [comment]
Weird. This didn't use to be this way. Points to needing some visual regression tests for the tour mode.

**Comment by nstrayer** [comment]
Will be fixed by #239
