### ISSUE TITLE
checkbox group inputId persists when switching focus to new checkbox group

### ISSUE THREAD

**Issue by amackey** [rstudio/shinyuieditor#243]
reproducible bug:

create a new checkbox group and set the inputId to "group A"; create a second checkbox group and set the inputId to "group B"; then click around between different items, and see the inputId's not stay in sync with current focus.

**Comment by nstrayer** [comment]
Oh good catch! Should be an easy fix.

**Comment by nstrayer** [comment]
Fix is in #245. Should be merged once all the CI stuff finishes!
