### ISSUE TITLE
Enhance navigation within How-To section

### ISSUE THREAD

**Issue by rpodcast** [rstudio/shinyuieditor#244]
Perhaps I've been too spoiled by pages built with R-Markdown and Quarto, but I think having a small table of contents box in the upper corner in the [How-To](https://rstudio.github.io/shinyuieditor/how-to/) page of the documentation site would give an easy way to see exactly what topics are covered. For example, I was having a heck of a time figuring out how to change the number of rows or columns in the grid containers, until I stumbled upon the controls that display when hovering over an edge. Then, sure enough, I see a couple of sections in the How-To page demonstrating that functionality. But I didn't realize those sections were available until scrolling down in the page.

**Comment by nstrayer** [comment]
This is a great point! It shouldn't be too bad to add. It's one of the downsides of rolling your own site I guess!

**Comment by nstrayer** [comment]
<img width="876" alt="image" src="https://github.com/rstudio/shinyuieditor/assets/6764693/1615c02b-d808-4483-aa48-7e9d4e49776c">
Added a fairly basic TOC for the article pages. When I get some more time I'll look into the floating mode on desktop etc..

**Comment by rpodcast** [comment]
Looks terrific! Thank you for updating the site so quickly.
