### ISSUE TITLE
install in windows still fails

### ISSUE THREAD

**Issue by apsteinmetz** [rstudio/shinyuieditor#53]
```
 Getting 1 pkg with unknown size
v Cached copy of shinyuieditor 0.0.1.0 (source) is the latest build
v No downloads needed, all packages are cached           
i Packaging shinyuieditor 0.0.1.0
! The shinyuieditor package has very long paths. The installation will probably
fail because most Windows versions do not support long paths. Please tell the
package authors about this.
x Failed to create source package shinyuieditor 0.0.1.0  

```

My install method is to clone the repo and build it locally.

**Comment by kulturevulture** [comment]
Also can't install on Windows 10

**Comment by kulturevulture** [comment]
Also can't install on Windows 10, R 4.0.4.
I'm using: remotes::install_github("rstudio/shinyuieditor", dependencies=TRUE)
* installing *source* package 'pkgload' ...
** package 'pkgload' successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
Calls: source -> file
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'renv/activate.R': No such file or directory
Execution halted
ERROR: lazy loading failed for package 'pkgload'
* removing 'C:xxxxxx'
*Also tried: pak::pkg_install('rstudio/shinyuieditor@development')
Error: Failed to build source package 'shinyuieditor'

**Comment by kulturevulture** [comment]
Success! I was able to install shinyuieditor on Windows 10.
 I had to update to RStudio 2922.07.1, R 4.2.1, and Rtools 4.2. 
Used: pak::pkg_install('rstudio/shinyuieditor@development',lib=.libPaths()[1])

**Comment by kulturevulture** [comment]
Hi Nick,
Yes, this item can be closed. Thank you.

Regards,
Mark
[Abbott Logo]
Mark Anawis, MA, ASQ CSSBB
(he/him/his)
Principal R&D Quality Engineer
Advanced Analytics
ADD R&D Quality Engineering
Abbott
100 Abbott Park Rd
Dept 09B6/AP20-4
Abbott Park, IL, 60064
O:
+1 224-667-4347
M:
+1 847-989-2084
***@***.******@***.***>
mark-anawis-539501a<http://linkedin.com/in/mark-anawis-539501a>
***@***.***<https://www.linkedin.com/company/abbott->

This communication may contain information that is proprietary, confidential, or exempt from disclosure. If you are not the intended recipient, please note that any other dissemination, distribution, use or copying of this communication is strictly prohibited. Anyone who receives this message in error should notify the sender immediately by telephone or by return e-mail and delete it from his or her computer.
