### ISSUE TITLE
On Firefox, numeric inputs render poorly

### ISSUE THREAD

**Issue by jcheng5** [rstudio/shinyuieditor#60]
Note especially the Width one is unusable, as is the Gap Size one (not pictured here). Tested on Firefox 102.0.1 (64-bit), macOS Monterey 12.4 (21F79).

<img width="223" alt="image" src="https://user-images.githubusercontent.com/129551/180713829-239fa358-746b-4611-a9f5-4a0ce068caaf.png">

**Comment by nstrayer** [comment]
Fixed in #103
