### ISSUE TITLE
UI editor does not launch with Rstudio Workbench

### ISSUE THREAD

**Issue by mohmhm1** [rstudio/shinyuieditor#69]
Upon installing the UIeditor and either launching from an existing app or a new one, workbench will display a blank browser window. Tried appending the port specified in the console to workbench IP address but returns an error

**Comment by nstrayer** [comment]
This is due to me creating urls for the editor in a way that workbench can detect and properly proxy. Shouldn't be too bad to fix but I will need to connect with those familiar to set it up! Sorry for the inconvenience!
