### ISSUE TITLE
Support for `shiny::navbarPage()`

### ISSUE THREAD

**Issue by ohovey5** [rstudio/shinyuieditor#76]
just tried this package and immediately get this error "unknown ui output: navbarPage", is navbarPage not supported yet?

**Comment by nstrayer** [comment]
`navbarPage` is not yet supported, no. See the "Can I use a different page type other than gridlayout?" section of the [FAQs](https://rstudio.github.io/shinyuieditor/articles/faqs.html). 

That being said one of the most urgent new features is new layouts so this will hopefully change shortly!

**Comment by GitHunter0** [comment]
Yes, this is the main thing missing in my opinion.

Nonetheless, `shinyuieditor` is a fantastic project.

**Comment by nstrayer** [comment]
This was just added in #91! Be sure to check it out and report any bugs you may find! Thanks so much for your feedback!
